from .Dummy import dummy_transmission_channels
from .Servicer import servicer_transmission_channels

action_transmission_channels = []
action_transmission_channels.extend(dummy_transmission_channels)
action_transmission_channels.extend(servicer_transmission_channels)