from ..Types import POKTType, Days, NumberOfBlocksType, PercentType, NanoSecondsType

servicer_parameter_set = {"name": "Servicer Parameter Set",
                       "notes": "",
                       "parameters": [{"variable_type": POKTType,
                                       "name": "minimum_stake_servicer",
                                       "description": "The minimum required stake for servicers, default is 15K",
                                       "symbol": None,
                                       "domain": None
                                       },
                                       {"variable_type": Days,
                                       "name": "minimum_stake_period_servicer",
                                       "description": "The minimum required period of time that a servicer has to be staked for, default is 21 days.",
                                       "symbol": None,
                                       "domain": None
                                       },
                                       {"variable_type": Days,
                                       "name": "minimum_pause_time",
                                       "description": "The minimum required period of time that a servicer has to be paused for before being able to be unpaused.",
                                       "symbol": None,
                                       "domain": None},
                                       {"variable_type": int,
                                       "name": "max_chains_servicer",
                                       "description": "When staking as a servicer, every servicer must register their stake for the Services that they support. Currently, servicers can register each stake to apply to their work in up to 15 different blockchains, which is the maximum number that can be chosen. ",
                                       "symbol": None,
                                       "domain": None},
                                       {"variable_type": NumberOfBlocksType,
                                        "name": "salary_block_frequency",
                                        "description": "The frequency of salary blocks for servicers",
                                        "symbol": None,
                                       "domain": None},
                                        {"variable_type": int,
                                        "name": "minimum_test_score_threshold",
                                        "description": "The minimum test scores to be eligible for salary for servicers",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": float,
                                        "name": "minimum_report_card_threshold",
                                        "description": "The minimum report card score to earn salary. Below the MinimumReportCardThreshold no reward is given to prevent cheap Sybil attacks and freeloading nodes.",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": NumberOfBlocksType,
                                        "name": "servicer_unbounding_period",
                                        "description": "The number of blocks before a servicer has their stake returned to them after unstaking.",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": POKTType,
                                        "name": "relays_to_tokens_multiplier",
                                        "description": """The amount of POKT rewarded for each relay in block rewards.""",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": PercentType,
                                        "name": "slash_fraction_downtime",
                                        "description": """The % of a node’s stake that is burned for downtime, where 1 is 100%.""",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": PercentType,
                                        "name": "replay_attack_burn_multiplier",
                                        "description": """The multiplier slash factor for submitting a replay attack. The base slash is directly proportional to the amount of relays claimed.""",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": NumberOfBlocksType,
                                        "name": "max_jailed_blocks",
                                        "description": """The amount of time (in blocks) a node has to unjail before being force unstaked and slashed.""",
                                        "symbol": None,
                                       "domain": None},
                                       {"variable_type": NanoSecondsType,
                                        "name": "downtime_jail_duration",
                                        "description": """The amount of time (in nanoseconds) before a node can unjail and resume service.""",
                                        "symbol": None,
                                       "domain": None}
                                       ]}

