from ..Types import uPOKTType, ServicerReportCardType, ServicerTestScoresType

servicer_state = {"name": "Servicer State",
              "notes": "",
              "variables": [{"type": uPOKTType,
                             "name": "Servicer Salary",
                             "description": "A ServicerSalary is assigned to each individual Servicer based on their specific ReportCard, and is distributed every SalaryBlockFrequency",
                             "symbol": None,
                             "domain": None},
                             {"type": ServicerReportCardType,
                             "name": "Report Card",
                             "description": "The report card used when determing salary for a servicer",
                             "symbol": None,
                             "domain": None},
                             {"type": ServicerTestScoresType,
                             "name": "Test Scores",
                             "description": "The QoS test scores",
                             "symbol": None,
                             "domain": None},
                             {"type": uPOKTType,
                             "name": "POKT Holdings",
                             "description": "The personal holdings of the servicer in uPOKT",
                             "symbol": None,
                             "domain": None},
                             {"type": uPOKTType,
                             "name": "Staked POKT",
                             "description": "The personal holdings of the servicer in uPOKT",
                             "symbol": None,
                             "domain": None}]}

