service_state = {"name": "Service State",
              "notes": "",
              "variables": [{"type": str,
                             "name": "Name",
                             "description": "The name of the service",
                             "symbol": None,
                             "domain": None},
                             {"type": str,
                             "name": "Portal API Prefix",
                             "description": "Prefix for the portal API",
                             "symbol": None,
                             "domain": None},
                             {"type": str,
                             "name": "Service ID",
                             "description": "The identifier used for the chain",
                             "symbol": None,
                             "domain": None}]}