from ..Types import uPOKTType, PublicKeyType, ServiceURLType, StakeStatusType

validator_state = {"name": "Validator State",
              "notes": "",
              "variables": [{"type": PublicKeyType,
                             "name": "Public key",
                             "description": "The identifier of the validator",
                             "symbol": None,
                             "domain": None},
                             {"type": uPOKTType,
                             "name": "POKT Holdings",
                             "description": "The personal holdings of the validator in uPOKT",
                             "symbol": None,
                             "domain": None},
                             {"type": uPOKTType,
                             "name": "Staked POKT",
                             "description": "The staked amount of the validator in uPOKT",
                             "symbol": None,
                             "domain": None},
                             {"type": ServiceURLType,
                             "name": "Service URL",
                             "description": "The API endpoint where the Web3 service is provided",
                             "symbol": None,
                             "domain": None},
                             {"type": PublicKeyType,
                             "name": "Operator Public Key",
                             "description": "OPTIONAL; The non-custodial pubKey operating this node",
                             "symbol": None,
                             "domain": None},
                             {"type": StakeStatusType,
                             "name": "Stake Status",
                             "description": "The status of staking for the actor",
                             "symbol": None,
                             "domain": None}]}

