from .Servicer import servicer_transmission_channels
from .Application import application_transmission_channels
from .Validator import validator_transmission_channels
from .Treasury import treasury_transmission_channels
from .DAO import dao_transmission_channels
from .Service import service_transmission_channels

state_update_transmission_channels = []
state_update_transmission_channels.extend(servicer_transmission_channels)
state_update_transmission_channels.extend(application_transmission_channels)
state_update_transmission_channels.extend(validator_transmission_channels)
state_update_transmission_channels.extend(treasury_transmission_channels)
state_update_transmission_channels.extend(dao_transmission_channels)
state_update_transmission_channels.extend(service_transmission_channels)
